parameters:
  - name: DB_NAME
    default: "SpecificationsTesting2"
    type: string
  - name: DB_HOSTNAME
    default: "10.10.10.124"
    type: string
  - name: DB_USERNAME
    default: "xyz"
    type: string
  - name: DB_PASSWORD
    default: "abc"
    type: string

jobs:
 - job: Build_DotNet
   displayName: 'Build DotNet'
   pool:
    vmImage: 'windows-latest'
   steps:
     - task: DotNetCoreCLI@2
       displayName: Restore
       inputs:
         command: 'restore'
         projects: |
            **/*.csproj
            
     - task: DotNetCoreCLI@2
       displayName: Build
       inputs:
         command: 'build'
         projects: '**/*.sln'
         arguments: --configuration $(buildConfiguration)