parameters:
  - name: connectionString
    displayName: 'Database connection string'
    type: string

jobs:
 - job: Publish_DotNet
   displayName: Publish
   pool:
    vmImage: 'windows-latest'
   steps:
     - task: DotNetCoreCLI@2
       displayName: Publish
       inputs:
         command: 'publish'
         publishWebProjects: false
         projects: |
             SpecificationsTestingV2/*.csproj
             !**/*Tests.csproj
         arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
         zipAfterPublish: True

     - task: PublishPipelineArtifact@1
       displayName: 'Publish Artifact'
       inputs:
         targetPath: $(Build.ArtifactStagingDirectory)
         artifact: 'SpecificationsTesting'

     - task: SendEmail@1
       inputs:
         To: 'mjw-tan@outlook.com'
         From: 'mjw-tan@outlook.com'
         Subject: 'New build artifact'
         Body: '$(System.TeamFoundationCollectionUri)$(System.TeamProject)/_apis/build/builds/$(Build.BuildId)/artifacts?artifactName=SpecificationsTesting&api-version=6.0'
         BodyAsHtml: false
         AddAttachment: false
         SmtpServer: 'smtp.gmail.com'
         SmtpUsername: 'mjw.tan@gmail.com'
         SmtpPassword: 'nhRp*4N5EB*Bi5'