//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomOrderVentilator
    {
        public int ID { get; set; }
        public int CustomOrderID { get; set; }
        public string Name { get; set; }
        public int CustomOrderMotorID { get; set; }
        public string AirVolume { get; set; }
        public string PressureTotal { get; set; }
        public string PressureStatic { get; set; }
        public string PressureDynamic { get; set; }
        public string RPM { get; set; }
        public Nullable<int> Efficiency { get; set; }
        public string ShaftPower { get; set; }
        public Nullable<int> SoundLevel { get; set; }
        public Nullable<int> SoundLevelTypeID { get; set; }
        public Nullable<int> BladeAngle { get; set; }
    
        public virtual CustomOrderMotor CustomOrderMotor { get; set; }
        public virtual CustomOrder CustomOrder { get; set; }
        public virtual SoundLevelType SoundLevelType { get; set; }
    }
}
