//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomOrderVentilatorTest
    {
        public int ID { get; set; }
        public int CustomOrderVentilatorID { get; set; }
        public Nullable<int> MeasuredVentilatorRPM { get; set; }
        public Nullable<int> MeasuredMotorRPM { get; set; }
        public Nullable<int> MeasuredBladeAngle { get; set; }
    
        public virtual CustomOrderVentilator CustomOrderVentilator { get; set; }
    }
}
