//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomOrderVentilator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomOrderVentilator()
        {
            this.CustomOrderVentilatorTests = new HashSet<CustomOrderVentilatorTest>();
        }
    
        public int ID { get; set; }
        public int CustomOrderID { get; set; }
        public int Amount { get; set; }
        public string Name { get; set; }
        public int CustomOrderMotorID { get; set; }
        public Nullable<int> VentilatorTypeID { get; set; }
        public string AirVolume { get; set; }
        public string PressureTotal { get; set; }
        public string PressureStatic { get; set; }
        public string PressureDynamic { get; set; }
        public string RPM { get; set; }
        public Nullable<int> Efficiency { get; set; }
        public string ShaftPower { get; set; }
        public Nullable<int> SoundLevel { get; set; }
        public Nullable<int> SoundLevelTypeID { get; set; }
        public Nullable<int> BladeAngle { get; set; }
        public string Atex { get; set; }
        public Nullable<int> GroupTypeID { get; set; }
        public Nullable<int> TemperatureClassID { get; set; }
        public Nullable<int> CatID { get; set; }
        public Nullable<int> CatOutID { get; set; }
    
        public virtual CatType CatType { get; set; }
        public virtual CustomOrderMotor CustomOrderMotor { get; set; }
        public virtual CustomOrder CustomOrder { get; set; }
        public virtual SoundLevelType SoundLevelType { get; set; }
        public virtual GroupType GroupType { get; set; }
        public virtual TemperatureClass TemperatureClass { get; set; }
        public virtual VentilatorType VentilatorType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomOrderVentilatorTest> CustomOrderVentilatorTests { get; set; }
    }
}
