//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomOrder()
        {
            this.CustomOrderVentilators = new HashSet<CustomOrderVentilator>();
        }
    
        public int ID { get; set; }
        public int CustomOrderNumber { get; set; }
        public int Type { get; set; }
        public string Debtor { get; set; }
        public string Reference { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> ATEXTypeID { get; set; }
        public Nullable<int> GroupTypeID { get; set; }
        public Nullable<int> TemperatureClassID { get; set; }
    
        public virtual ATEXType ATEXType { get; set; }
        public virtual GroupType GroupType { get; set; }
        public virtual TemperatureClass TemperatureClass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomOrderVentilator> CustomOrderVentilators { get; set; }
    }
}
