//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Motor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Motor()
        {
            this.Ventilators = new HashSet<Ventilator>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int TypeID { get; set; }
        public string Version { get; set; }
        public Nullable<int> IEC { get; set; }
        public Nullable<int> IP { get; set; }
        public string BuildingType { get; set; }
        public string ISO { get; set; }
        public Nullable<decimal> Power { get; set; }
        public Nullable<int> RPM { get; set; }
        public Nullable<int> Amperage { get; set; }
        public Nullable<int> StartupAmperage { get; set; }
        public Nullable<int> VoltageTypeID { get; set; }
        public Nullable<int> Frequency { get; set; }
        public Nullable<int> PowerFactor { get; set; }
    
        public virtual VoltageType VoltageType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ventilator> Ventilators { get; set; }
    }
}
