//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateVentilator
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> VentilatorTypeID { get; set; }
        public Nullable<int> AirVolume { get; set; }
        public Nullable<int> PressureTotal { get; set; }
        public Nullable<int> PressureStatic { get; set; }
        public Nullable<int> PressureDynamic { get; set; }
        public Nullable<int> RPM { get; set; }
        public Nullable<int> Efficiency { get; set; }
        public Nullable<int> ShaftPower { get; set; }
        public Nullable<int> SoundLevel { get; set; }
        public Nullable<int> SoundLevelTypeID { get; set; }
        public Nullable<int> BladeAngle { get; set; }
    
        public virtual SoundLevelType SoundLevelType { get; set; }
        public virtual VentilatorType VentilatorType { get; set; }
    }
}
