//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventilator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ventilator()
        {
            this.CustomOrders = new HashSet<CustomOrder>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int MotorID { get; set; }
        public Nullable<int> AirVolume { get; set; }
        public Nullable<int> PressureTotal { get; set; }
        public Nullable<int> PressureStatic { get; set; }
        public Nullable<int> PressureDynamic { get; set; }
        public Nullable<int> RPM { get; set; }
        public Nullable<int> Efficiency { get; set; }
        public Nullable<int> ShaftPower { get; set; }
        public Nullable<int> SoundLevel { get; set; }
        public Nullable<int> SoundLevelTypeID { get; set; }
        public Nullable<int> BladeAngle { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomOrder> CustomOrders { get; set; }
        public virtual Motor Motor { get; set; }
        public virtual SoundLevelType SoundLevelType { get; set; }
    }
}
